# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/MSI/IC_Design_project/IC_Design_project.cache/wt [current_project]
set_property parent.project_path C:/Users/MSI/IC_Design_project/IC_Design_project.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo c:/Users/MSI/IC_Design_project/IC_Design_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/MSI/IC_Design_project/BRAM_INPUT.coe
read_verilog -library xil_defaultlib -sv {
  C:/Users/MSI/IC_Design_project/IC_Design_project.srcs/sources_1/new/Blending.sv
  C:/Users/MSI/IC_Design_project/IC_Design_project.srcs/sources_1/new/Image_process_top.sv
  C:/Users/MSI/IC_Design_project/IC_Design_project.srcs/sources_1/new/normalization.sv
  C:/Users/MSI/IC_Design_project/IC_Design_project.srcs/sources_1/new/sharpening.sv
  C:/Users/MSI/IC_Design_project/IC_Design_project.srcs/sources_1/new/smoothening.sv
  C:/Users/MSI/IC_Design_project/IC_Design_project.srcs/sources_1/new/TOP_Module.sv
}
read_verilog -library xil_defaultlib C:/Users/MSI/IC_Design_project/IC_Design_project.srcs/sources_1/bd/BRAM/hdl/BRAM_wrapper.v
add_files C:/Users/MSI/IC_Design_project/IC_Design_project.srcs/sources_1/bd/BRAM/BRAM.bd
set_property used_in_implementation false [get_files -all c:/Users/MSI/IC_Design_project/IC_Design_project.srcs/sources_1/bd/BRAM/ip/BRAM_blk_mem_gen_0_0/BRAM_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/MSI/IC_Design_project/IC_Design_project.srcs/sources_1/bd/BRAM/BRAM_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top TOP_Module -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TOP_Module.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TOP_Module_utilization_synth.rpt -pb TOP_Module_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
